package:
    name: nrel-cloud_fs
    version: {{ environ.get('GIT_DESCRIBE_TAG','').replace('v', '', 1) }}

source:
    git_url: ../

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - s3fs
  run:
    - python
    - pip
    - s3fs

about:
  home: "https://github.com/NREL/cloud_fs"
  license: BSD 3-Clause
  summary: "Cloud file system utilities"
  doc_url: "https://nrel.github.io/cloud_fs"
  dev_url: "https://github.com/NREL/cloud_fs"
